#!/bin/sh

include_rt_api(){
	
	script_path=$(realpath $0)
	script_dir="$(dirname $script_path)"
	rtapi_path="$script_dir/include/rt-api"

	source $rtapi_path
}

usage(){
	echo "Usage: rt-uart-test [option]"
	echo ""
	echo "Runs rtuart_transport_test in preset environment."
	echo "Requires root privileges."
	echo ""
	echo "Options:"
	echo "  -f, --force"
	echo "    Force run test; configure run environment if needed."
	echo "    If -f is not specified test won't start in misconfigured environment."
	echo "  -h, --help"
	echo "    Show this message."
}

check_configuration(){

	if pcscd_is_running; then
		print_error "pcscd is running; kill pcscd or use -f option"
		exit 1
	fi

	if ! som_is_active; then
		print_error "Rutoken 4010 is not available; change available interfaces manually or use -f option"
		exit 1
	fi

	true
	return
}

trasport_test(){
	echo ""
	rtuart_transport_test $1
	echo ""
}

run(){

	exit_if_not_root

	pcscd_was_running=false

	if [ "$1" = "force" ]; then

		if pcscd_is_running; then
			stop_pcscd
			pcscd_was_running=true
		fi

		memorize_devices

		enable_som

	else
		check_configuration
	fi

	trasport_test "/dev/ttyAMA0"

	restore_devices

	if ! $pcscd_was_running; then
		stop_pcscd
	fi
}

main(){

	if [ $# -eq 0 ]
	then
		run
		exit 1
	fi

	case $1 in
		-f | --force)
			run "force"
			exit 0
		;;
		-h | --help)
			usage
			exit 0
		;;
		*)
			usage
			exit 1
		;;
	esac
}

include_rt_api
main $1
